<a href="https://colab.research.google.com/github/Umair505/deep-learning-journey/blob/main/Week_01/perceptron_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [23]:
class Perceptron:
  def __init__(self,eta,epochs):
    self.weights = np.random.randn(3) * 1e-4
    print(f"Self.weights {self.weights}")

    self.eta = eta
    self.epochs = epochs


  def activationFunction(self,input,weights):
    z = np.dot(input,weights)
    return np.where(z>0,1,0)

  def fit(self,X,y):
    self.X = X
    self.y = y

    for epoch in range(self.epochs):
      print("Epoch: ",epoch)
      x_with_bias = np.c_[self.X,-np.ones((len(self.X),1))]
      print(f"X with bias {x_with_bias}")
      y_pred = self.activationFunction(x_with_bias,self.weights)
      print(f"Predicted value {y_pred}")

      error = self.y - y_pred
      print(f"Error \n{error}")
      #weight update

      self.weights = self.weights + self.eta * np.dot(x_with_bias.T,error)
      print(f"Updated weight \n {self.weights}")


def predict(self,X):
  x_with_bias = np.c_[X,-np.ones((len(X),1))]

  return self.activationFunction(x_with_bias,self.weights)


data = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,0,0,1]
}
AND = pd.DataFrame(data)

X = AND.drop('y',axis=1)
y = AND['y']

In [24]:
#Model Prediction
model = Perceptron(eta = 0.5,epochs=10)
model.fit(X,y)

Self.weights [ 1.52302986e-04 -2.34153375e-05 -2.34136957e-05]
Epoch:  0
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [1 0 1 1]
Error
0   -1
1    0
2   -1
3    0
Name: y, dtype: int64
Updated weight
 [-4.99847697e-01 -2.34153375e-05  9.99976586e-01]
Epoch:  1
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 0 0 0]
Error
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weight
 [1.52302986e-04 4.99976585e-01 4.99976586e-01]
Epoch:  2
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
 [1.52302986e-04 4.99976585e-01 4.99976586e-01]
Epoch:  3
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
 [1.52302986e-04 4.99976585e-01 4.99976586e-01]
Epoch:  4
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
 [1.52302986e-04 4.99976585e-01 4.99976586e-01]
Epoch:  5
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
 [1.52302986e-04 4.99976585e-01 4.99976586e-01]
Epoch:  6
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
 [1.52302986e-04 4.99976585e-01 4.99976586e-01]
Epoch:  7
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
 [1.52302986e-04 4.99976585e-01 4.99976586e-01]
Epoch:  8
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
 [1.52302986e-04 4.99976585e-01 4.99976586e-01]
Epoch:  9
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
 [1.52302986e-04 4.99976585e-01 4.99976586e-01]

##OR GATE

In [25]:
data = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,1,1,1]
}
OR = pd.DataFrame(data)

X = OR.drop('y',axis=1)
y = OR['y']
#Model Prediction
model = Perceptron(eta = 0.5,epochs=10)
model.fit(X,y)

Self.weights [ 1.57921282e-04  7.67434729e-05 -4.69474386e-05]
Epoch:  0
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [1 1 1 1]
Error
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
 [1.57921282e-04 7.67434729e-05 4.99953053e-01]
Epoch:  1
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 0 0 0]
Error
0    0
1    1
2    1
3    1
Name: y, dtype: int64
Updated weight
 [ 1.00015792  1.00007674 -1.00004695]
Epoch:  2
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [1 1 1 1]
Error
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
 [ 1.00015792  1.00007674 -0.50004695]
Epoch:  3
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [1 1 1 1]
Error
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
 [ 1.00015792e+00  1.00007674e+00 -4.69474386e-05]
Epoch:  4
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [1 1 1 1]
Error
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
 [1.00015792 1.00007674 0.49995305]
Epoch:  5
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 1 1 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
 [1.00015792 1.00007674 0.49995305]
Epoch:  6
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 1 1 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
 [1.00015792 1.00007674 0.49995305]
Epoch:  7
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 1 1 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
 [1.00015792 1.00007674 0.49995305]
Epoch:  8
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 1 1 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
 [1.00015792 1.00007674 0.49995305]
Epoch:  9
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 1 1 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
 [1.00015792 1.00007674 0.49995305]

##XOR GATE

In [26]:
data = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,1,1,0]
}
XOR = pd.DataFrame(data)

X = XOR.drop('y',axis=1)
y = XOR['y']
#Model Prediction
model = Perceptron(eta = 0.5,epochs=10)
model.fit(X,y)

Self.weights [ 5.42560044e-05 -4.63417693e-05 -4.65729754e-05]
Epoch:  0
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [1 1 1 1]
Error
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weight
 [-0.49994574 -0.50004634  0.99995343]
Epoch:  1
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 0 0 0]
Error
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weight
 [ 5.42560044e-05 -4.63417693e-05 -4.65729754e-05]
Epoch:  2
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [1 1 1 1]
Error
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weight
 [-0.49994574 -0.50004634  0.99995343]
Epoch:  3
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 0 0 0]
Error
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weight
 [ 5.42560044e-05 -4.63417693e-05 -4.65729754e-05]
Epoch:  4
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [1 1 1 1]
Error
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weight
 [-0.49994574 -0.50004634  0.99995343]
Epoch:  5
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 0 0 0]
Error
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weight
 [ 5.42560044e-05 -4.63417693e-05 -4.65729754e-05]
Epoch:  6
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [1 1 1 1]
Error
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weight
 [-0.49994574 -0.50004634  0.99995343]
Epoch:  7
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 0 0 0]
Error
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weight
 [ 5.42560044e-05 -4.63417693e-05 -4.65729754e-05]
Epoch:  8
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [1 1 1 1]
Error
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weight
 [-0.49994574 -0.50004634  0.99995343]
Epoch:  9
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted value [0 0 0 0]
Error
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weight
 [ 5.42560044e-05 -4.63417693e-05 -4.65729754e-05]

In [4]:
random_normal1 = np.random.seed(42)

In [7]:
import pandas as pd

data = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,0,0,1]
}
AND = pd.DataFrame(data)
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [13]:
X = AND.drop('y',axis=1)
y = AND['y']
y

0    0
1    0
2    0
3    1
Name: y, dtype: int64

In [14]:
bias = -np.ones((len(x),1))
bias

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [17]:
bias  = np.c_[X,-np.ones((len(x),1))]
bias

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])